language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer install

script:
  - ./bin/phpunit
  - ./bin/phpcs --standard=phpcs.xml --extensions=php --report=checkstyle --report-file=build/logs/checkstyle.xml lib

after_script:
  - ./bin/coveralls -v
